enum Keys {
  POST_COVER_LETTER = 'POST_COVER_LETTER',
  GET_COVER_LETTER = 'GET_COVER_LETTER',
  GET_COVER_LETTERS = 'GET_COVER_LETTERS',
  PATCH_COVER_LETTER = 'PATCH_COVER_LETTER',
  POST_COVER_LETTER_FOR_JOB = 'POST_COVER_LETTER_FOR_JOB',
  DELETE_COVER_LETTER = 'DELETE_COVER_LETTER',
  POST_COVER_LETTER_ASK_WIZARD = 'POST_COVER_LETTER_ASK_WIZARD',
  POST_COVER_LETTER_WIZARD = 'POST_COVER_LETTER_WIZARD',
}

export default Keys;
