enum Keys {
  POST_COVER_LETTER = 'POST_COVER_LETTER',
  GET_COVER_LETTER = 'GET_COVER_LETTER',
  GET_COVER_LETTERS = 'GET_COVER_LETTERS',
  PATCH_COVER_LETTER = 'PATCH_COVER_LETTER',
}

export default Keys;
