version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: akpa_strapi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      DB_HOST: "postgres"
    ports:
      - "5432:5432" # Optional: only needed if you want to access the DB from the host
    volumes:
      - pgdata:/var/lib/postgresql/data

  strapi:
    image: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: akpa_strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: postgres
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-app:/srv/app
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
