enum Keys {
  SIGN_UP = 'SIGN_UP',
  REQUEST_NEW_PASSWORD = 'REQUEST_NEW_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  GET_PROFILE = 'GET_PROFILE',
  CONFIRM_USER = 'CONFIRM_USER',
  UPDATE_USER = 'UPDATE_USER',
  PATCH_USER = 'PATCH_USER',
  POST_SKILL = 'POST_SKILL',
  GET_SKILLS = 'GET_SKILLS',
  DELETE_SKILL = 'DELETE_SKILL',
  REQUEST_VERIFICATION = 'REQUEST_VERIFICATION',
}

export default Keys;
