enum Keys {
  SIGN_UP = 'SIGN_UP',
  REQUEST_NEW_PASSWORD = 'REQUEST_NEW_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  GET_PROFILE = 'GET_PROFILE',
  CONFIRM_USER = 'CONFIRM_USER',
  UPDATE_USER = 'UPDATE_USER',
}

export default Keys;
