image: node:18

options:
max-time: 10

definitions:
  caches:
    api-node:
      path: nest-rest-api/node_modules
    ui-node:
      path: react-app/node_modules
  services:
    docker:
      memory: 4096

install-dep-api: &install-dep-api
  step:
    name: Install api dependencies
    script:
      - cd nest-rest-api
      - npm i
    caches:
      - api-node

install-dep-ui: &install-dep-ui
  step:
    name: Install ui dependencies
    script:
      - cd react-app
      - npm i
    caches:
      - ui-node

build-api: &build-api
  step:
    name: Build api
    script:
      - cd nest-rest-api
      - npm run prisma:generate
      - npm run build
    caches:
      - api-node

build-ui: &build-ui
  step:
    name: Build UI
    script:
      - cd react-app
      - npm run build:dev
    caches:
      - ui-node

deploy-api-infrastructure-dev: &deploy-api-infrastructure-dev
  step:
    name: DEV - Deploy api infrastructure
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd nest-rest-api/infrastructure
      - ENVIRONMENT=dev ./deploy.sh

deploy-api-infrastructure-prod: &deploy-api-infrastructure-prod
  step:
    name: PROD - Deploy api infrastructure
    trigger: manual
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd nest-rest-api/infrastructure
      - ENVIRONMENT=prod ./deploy.sh

build-api-and-push-to-ecr-dev: &build-api-and-push-to-ecr-dev
  step:
    name: DEV - Build docker image for api and deploy to AWS ECR
    caches:
      - docker
    services:
      - docker
    size: 2x
    script:
      - cd nest-rest-api
      - docker build --target production -t akpa-ai-repository-dev:latest .
      - pipe: atlassian/aws-ecr-push-image:2.2.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          IMAGE_NAME: akpa-ai-repository-dev

build-api-and-push-to-ecr-prod: &build-api-and-push-to-ecr-prod
  step:
    name: PROD - Build docker image for api and deploy to AWS ECR
    caches:
      - docker
    services:
      - docker
    size: 2x
    script:
      - cd nest-rest-api
      - docker build --target production -t akpa-ai-repository-prod:latest .
      - pipe: atlassian/aws-ecr-push-image:2.2.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          IMAGE_NAME: akpa-ai-repository-prod

build-migrations-and-push-to-ecr-dev: &build-migrations-and-push-to-ecr-dev
  step:
    name: DEV - Build docker image for migrations and deploy to AWS ECR
    caches:
      - docker
    services:
      - docker
    size: 2x
    script:
      - cd nest-rest-api
      - docker build -f Dockerfile.prisma.migrate -t akpa-ai-db-migration-repository-dev:latest .
      - pipe: atlassian/aws-ecr-push-image:2.2.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          IMAGE_NAME: akpa-ai-db-migration-repository-dev

build-migrations-and-push-to-ecr-prod: &build-migrations-and-push-to-ecr-prod
  step:
    name: PROD - Build docker image for migrations and deploy to AWS ECR
    caches:
      - docker
    services:
      - docker
    size: 2x
    script:
      - cd nest-rest-api
      - docker build -f Dockerfile.prisma.migrate -t akpa-ai-db-migration-repository-prod:latest .
      - pipe: atlassian/aws-ecr-push-image:2.2.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          IMAGE_NAME: akpa-ai-db-migration-repository-prod

build-strapi-and-push-to-ecr-dev: &build-strapi-and-push-to-ecr-dev
  step:
    name: DEV - Build docker image for Strapi and deploy to AWS ECR
    caches:
      - docker
    services:
      - docker
    size: 2x
    script:
      - cd asset-api
      - docker build -t akpa-ai-strapi-repository-dev:latest .
      - pipe: atlassian/aws-ecr-push-image:2.2.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          IMAGE_NAME: akpa-ai-strapi-repository-dev

build-strapi-and-push-to-ecr-prod: &build-strapi-and-push-to-ecr-prod
  step:
    name: PROD - Build docker image for Strapi and deploy to AWS ECR
    caches:
      - docker
    services:
      - docker
    size: 2x
    script:
      - cd asset-api
      - docker build -t akpa-ai-strapi-repository-prod:latest .
      - pipe: atlassian/aws-ecr-push-image:2.2.0
        variables:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
          IMAGE_NAME: akpa-ai-strapi-repository-prod

deploy-to-ec2-dev: &deploy-to-ec2-dev
  step:
    name: DEV - Deploy to AWS EC2
    size: 2x
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd nest-rest-api/deployment
      - ENVIRONMENT=dev ./env.sh
      - echo "{\"BITBUCKET_COMMIT\":\"$BITBUCKET_COMMIT\",\"BITBUCKET_BUILD_NUMBER\":\"$BITBUCKET_BUILD_NUMBER\"}" > ./deployment.json
      - pipe: atlassian/scp-deploy:1.4.1
        variables:
          USER: ubuntu
          SERVER: $SERVER_IP_DEV
          REMOTE_PATH: "/home/ubuntu/"
          LOCAL_PATH: "${BITBUCKET_CLONE_DIR}/nest-rest-api/deployment"
          SSH_KEY: $SSH_KEY_DEV
          EXTRA_ARGS: ["-o", "StrictHostKeyChecking=no"]
      - pipe: atlassian/ssh-run:0.7.1
        variables:
          SSH_USER: ubuntu
          SERVER: $SERVER_IP_DEV
          SSH_KEY: $SSH_KEY_DEV
          MODE: script
          COMMAND: "${BITBUCKET_CLONE_DIR}/nest-rest-api/deployment/migrate.sh"
          ENV_VARS: >-
            ENVIRONMENT=dev
      - pipe: atlassian/ssh-run:0.7.1
        variables:
          SSH_USER: ubuntu
          SERVER: $SERVER_IP_DEV
          SSH_KEY: $SSH_KEY_DEV
          MODE: script
          COMMAND: "${BITBUCKET_CLONE_DIR}/nest-rest-api/deployment/spinup-docker-compose.sh"
          ENV_VARS: >-
            ENVIRONMENT=dev
            API_HOST=api-dev.akpa.softup.co
            STRAPI_HOST=strapi-dev.akpa.softup.co

deploy-to-ec2-prod: &deploy-to-ec2-prod
  step:
    name: PROD - Deploy to AWS EC2
    size: 2x
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd nest-rest-api/deployment
      - ENVIRONMENT=prod ./env.sh
      - echo "{\"BITBUCKET_COMMIT\":\"$BITBUCKET_COMMIT\",\"BITBUCKET_BUILD_NUMBER\":\"$BITBUCKET_BUILD_NUMBER\"}" > ./deployment.json
      - pipe: atlassian/scp-deploy:1.4.1
        variables:
          USER: ubuntu
          SERVER: $SERVER_IP_PROD
          REMOTE_PATH: "/home/ubuntu/"
          LOCAL_PATH: "${BITBUCKET_CLONE_DIR}/nest-rest-api/deployment"
          SSH_KEY: $SSH_KEY_PROD
          EXTRA_ARGS: ["-o", "StrictHostKeyChecking=no"]
      - pipe: atlassian/ssh-run:0.7.1
        variables:
          SSH_USER: ubuntu
          SERVER: $SERVER_IP_PROD
          SSH_KEY: $SSH_KEY_PROD
          MODE: script
          COMMAND: "${BITBUCKET_CLONE_DIR}/nest-rest-api/deployment/migrate.sh"
          ENV_VARS: >-
            ENVIRONMENT=prod
      - pipe: atlassian/ssh-run:0.7.1
        variables:
          SSH_USER: ubuntu
          SERVER: $SERVER_IP_PROD
          SSH_KEY: $SSH_KEY_PROD
          MODE: script
          COMMAND: "${BITBUCKET_CLONE_DIR}/nest-rest-api/deployment/spinup-docker-compose.sh"
          ENV_VARS: >-
            ENVIRONMENT=prod
            API_HOST=api.akpa.softup.co
            STRAPI_HOST=strapi.akpa.softup.co

test-api: &test-api
  step:
    name: Test api
    script:
      - cd nest-rest-api
      - npm test
    caches:
      - api-node

test-ui: &test-ui
  step:
    name: Test ui
    script:
      - cd react-app
      - npm test
    caches:
      - ui-node

deploy-frontend-infrastructure-dev: &deploy-frontend-infrastructure-dev
  step:
    name: DEV - Deploy Frontend infrastructure
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd react-app/infrastructure
      - ENVIRONMENT=dev ./deploy.sh

deploy-frontend-infrastructure-prod: &deploy-frontend-infrastructure-prod
  step:
    name: PROD - Deploy Frontend infrastructure
    trigger: manual
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd react-app/infrastructure
      - ENVIRONMENT=prod ./deploy.sh

deploy-route-53: &deploy-route-53
  step:
    name: Deploy Route 53 Hosted Zone
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd infrastructure
      - ./akpa-ai-route53.sh

frontend-build-dev: &frontend-build-dev
  step:
    name: DEV - Run Frontend Build
    caches:
      - ui-node
    script:
      - cd react-app
      - npm run build:dev
    artifacts:
      - react-app/dist/**

frontend-build-prod: &frontend-build-prod
  step:
    name: PROD - Run Frontend Build
    caches:
      - ui-node
    script:
      - cd react-app
      - npm run build:prod
    artifacts:
      - react-app/dist/**

publish-frontend-dev: &publish-frontend-dev
  step:
    name: DEV - Publish Frontend In S3
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd react-app/infrastructure
      - ENVIRONMENT=dev ./publish.sh

publish-frontend-prod: &publish-frontend-prod
  step:
    name: PROD - Publish Frontend In S3
    image: atlassian/pipelines-awscli:1.29.35
    script:
      - cd react-app/infrastructure
      - ENVIRONMENT=prod ./publish.sh

pipelines:
  pull-requests:
    "feature/api/*":
      - <<: *install-dep-api
      - <<: *build-api
    "feature/ui/*":
      - <<: *install-dep-ui
      - <<: *build-ui

  branches:
    master:
      - parallel:
          - <<: *install-dep-api
          - <<: *install-dep-ui
      - parallel:
          - <<: *deploy-api-infrastructure-dev
          - <<: *deploy-frontend-infrastructure-dev
          - <<: *deploy-route-53
      - parallel:
          - <<: *build-api-and-push-to-ecr-dev
          - <<: *build-migrations-and-push-to-ecr-dev
          - <<: *build-strapi-and-push-to-ecr-dev
      - <<: *deploy-to-ec2-dev
      - <<: *frontend-build-dev
      - <<: *publish-frontend-dev
      - parallel:
          - <<: *deploy-api-infrastructure-prod
          - <<: *deploy-frontend-infrastructure-prod
      - parallel:
          - <<: *build-api-and-push-to-ecr-prod
          - <<: *build-migrations-and-push-to-ecr-prod
          - <<: *build-strapi-and-push-to-ecr-prod
      - <<: *deploy-to-ec2-prod
      - <<: *frontend-build-prod
      - <<: *publish-frontend-prod
