enum Keys {
  POST_JOB = 'POST_JOB',
  GET_JOB = 'GET_JOB',
  GET_JOBS = 'GET_JOBS',
  GET_RECOMMENDED_JOBS = 'GET_RECOMMENDED_JOBS',
  PATCH_JOB = 'PATCH_JOB',
  POST_JOB_TIPS_AND_ADVICES = 'POST_JOB_TIPS_AND_ADVICES',
}

export default Keys;
