AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront OAC for Akpa Ai

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String

Resources:
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
          Name: !Sub SoftupXOAC-${EnvironmentName}
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

Outputs:
  OriginAccessControlID:
    Description: ID of the Akpa Ai OAC
    Value: !GetAtt OriginAccessControl.Id
