export enum Route {
  ROOT = '/',
  YOUTH_CAREER_ORIENTATION = 'youth-career-orientation',
  RESUME = 'resume',
  COVER_LETTER = 'cover-letter',
  JOBS = 'jobs',
  TRAINING = 'training',
  ACCESS = '/access',
  LOGIN = 'login',
  SIGNUP = 'signup',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_PASSWORD = 'reset-password',
  CONFIRM_USER = 'confirm-user',
  PROFILE_SETTINGS = 'profile-settings',
  PERSONAL_INFO = '/profile-settings/personal-info',
}
