export enum Route {
  ROOT = '/',
  YOUTH_CAREER_ORIENTATION = 'youth-career-orientation',
  RESUME = 'resume',
  COVER_LETTERS = 'cover-letters',
  COVER_LETTERS_DETAILS = 'cover-letters/:id',
  JOBS = 'jobs',
  JOB_DETAILS = 'jobs/:id',
  JOB_INTERVIEW_TIPS = 'jobs/:id/interview-tips',
  TRAINING = 'training',
  TRAINING_VIDEOS = '/training/videos',
  TRAINING_ARTICLES = '/training/articles',
  ACCESS = '/access',
  LOGIN = 'login',
  SIGNUP = 'signup',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_PASSWORD = 'reset-password',
  CONFIRM_USER = 'confirm-user',
  PROFILE_SETTINGS = 'profile-settings',
  PERSONAL_INFO = '/profile-settings/personal-info',
  SKILLS_AND_HOBBIES = '/profile-settings/skills-and-hobbies',
  CHANGE_PASSWORD = '/profile-settings/change-password',
  MY_RESUME = '/profile-settings/my-resume',
  CREATE_RESUME = '/profile-settings/create-resume',
  RESUME_QUESTIONNAIRE = 'resume-questionnaire',
  COVER_LETTER_QUESTIONNAIRE = 'cover-letter-questionnaire',
  RESUME_DETAILS = '/resumes/:id',
}
