AWSTemplateFormatVersion: 2010-09-09
Description: Akpa Ai ECR

Parameters:
  EnvironmentName:
    Description: Environment name
    Type: String

Resources:
  AkpaECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub akpa-ai-repository-${EnvironmentName}

  AkpaDbMigrationRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub akpa-ai-db-migration-repository-${EnvironmentName}

  AkpaStrapiRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: false
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: MUTABLE
      RepositoryName: !Sub akpa-ai-strapi-repository-${EnvironmentName}

Outputs:
  AkpaECRRepositoryName:
    Description: Repository name
    Value: !Ref AkpaECRRepository
  AkpaECRRepositoryArn:
    Description: Akpa ecr arn
    Value: !GetAtt AkpaECRRepository.Arn
  AkpaECRRepositoryUri:
    Description: Akpa ecr URI
    Value: !GetAtt AkpaECRRepository.RepositoryUri

  AkpaDbMigrationRepositoryName:
    Description: DB migration Repository name
    Value: !Ref AkpaDbMigrationRepository
  AkpaDbMigrationRepositoryArn:
    Description: Akpa DB migration ecr arn
    Value: !GetAtt AkpaDbMigrationRepository.Arn
  AkpaDbMigrationRepositoryUri:
    Description: Akpa DB migration ecr URI
    Value: !GetAtt AkpaDbMigrationRepository.RepositoryUri

  AkpaStrapiRepositoryName:
    Description: Strapi Repository name
    Value: !Ref AkpaStrapiRepository
  AkpaStrapiRepositoryArn:
    Description: Akpa Strapi ecr arn
    Value: !GetAtt AkpaStrapiRepository.Arn
  AkpaStrapiRepositoryUri:
    Description: Akpa Strapi ecr URI
    Value: !GetAtt AkpaStrapiRepository.RepositoryUri
