AWSTemplateFormatVersion: 2010-09-09
Description: Softup X api lambda role

Parameters:
  ArtifactsBucket:
    Description: S3 bucket where source code packages are
    Type: String
  EnvironmentName:
    Description: Environment name
    Type: String

# Example how to use Conditions
# !If [IsProd, ['value for prod'], ['value for else']]
Conditions:
  IsProd: !Equals [!Sub '${EnvironmentName}', 'prod']

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-write-cloudwatch
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
        - PolicyName: !Sub ${AWS::StackName}-network-interface
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'
        - PolicyName: !Sub ${AWS::StackName}-artifact-read
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactsBucket}
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactsBucket}/*

Outputs:
  LambdaRoleArn:
    Description: Lambda execution role ARN
    Value: !GetAtt LambdaRole.Arn
