import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class ResumeAutoGenerateDto {
  @IsNotEmpty()
  @IsString()
  @ApiProperty({ type: String })
  content: string;
}
