AWSTemplateFormatVersion: "2010-09-09"
Description: Hosted zones of Akpa Ai

Resources:
  DNS:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: "Hosted zone for managing Akpa Ai DNS entries"
      Name: "softup.x"

Outputs:
  SoftupXZoneId:
    Description: ID of the Hosted Zone for softup.x
    Value: !Ref DNS
