AWSTemplateFormatVersion: "2010-09-09"
Description: Hosted zones of Akpa Ai

Resources:
  DNS:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    Properties:
      HostedZoneConfig:
        Comment: "Hosted zone for managing Akpa Ai DNS entries"
      Name: "akpa.softup.co"

Outputs:
  AkpaHostedZoneId:
    Description: ID of the Hosted Zone for akpa.ai
    Value: !Ref DNS
