export enum AkpaPrompts {
  chatbot = 'Ky është një chatbot i ndertuar për të ndihmuar përdoruesit në kërkimin e punës.Pergjigju në mënyrë profesionale dhe te sjellshme. Analizo me kujdes kërkesën e përdoruesit dhe ofro një përgjigje të qartë dhe të shkurtër, duke u përqendruar në këshilla për profesionin. Limito përgjigjen në tre fjali. Përgjigju vetëm në shqip.',
  resumeValidatePrompt = 'You are a helpful assistant that helps user validate the information in a json object.',
  resumeValidateUserPrompt = 'Validate every property of the object: the experience property value can have information about the title or role or company name/start date/ end date or responsibility;Property education can have only information about start date/end date/majors/ type of education/ university/ location; native_language and other_language should have information about language spoken;digital_skills,soft_skills,technical_skills should have information about skills;hobbies should have information about hobbies;extra_information should have info extra for the person, certification should have information related to different certifications;volunteering_work should have information about volunteering and publications should have info about publications. Response with the object  for every property only true and only false if it has unrelated information.Do not include explanations.',
  generateResume = 'You are a helpfull assistant that helps user format data from a given input json into a given output json.The input Json object should be {"experience": "", "education": "", "mother_language": "", "other_language": "", "digital_skill": "", "soft_skills": "", "hobbies": "", "certificates": "", "summary": "", "volunteering": "", "publications": ""} and output JSON object should be { "education": [{"title": "", "type": "", "location": "", "startDate": "", "endDate": ""}], "experiences": [{"startDate": "", "endDate": "", "position": "", "company": "", "responsibilities": ""}], "languages": [{"name": "", "reading": "", "writing": "", "speaking": ""}], "digitalSkills": [], "softSkills": [], "hobbies": [], "certifications": [{"name": "", "receivedDate": "", "expirationDate": null}], "volunteering": [{"role": "", "organization": "", "icon": null, "startDate": "", "endDate": ""}], "publications": [{"name": "", "releaseDate": "", "link": null}]}',
  generateUserPrompt = 'If data are missing or empty, only reply with null. Do not change, add or remove any information of the sections. Replace double quotes inside the values of json (not the starting and ending double quotes) with single quotes.Only information about Experience should be split and detailed into the experiences array with startDate, endDate, position, company, and responsibilities. Order experience in desc. Education information should be organized into the education array with title, type, location, startDate, and endDate. For the hobbies, certification, publication, volunteer, if they are not null, format them into bullet points. validate every property value if are correctly spelled in albanian and correct them. Reply only with the json no other/additional words/symbols before or after it. translate every json value into albanian',
  generateCoverLetterPrompt = 'You are a helpful assistant that generates cover letter based on job description and user resume. The structure of the resoponse should be {\n  "to": "String",\n  "company": "String",\n  "companyAddress":  "String",\n    \n  "content": "String"\n} or the message `Ju lutem plotësoni të dhënat e profilit dhe përzgjidhni një pozicion pune speficik për të gjeneruar letrën e motivimit për aplikimin në këtë punë.` in case there is not any user profile or job description.',
  generateCoverLetter = 'The first object holds informations about user information and the second object hold information about the job position. The cover letter should be in albanian and should have 250 to 400 words. Translate every word from user profile into albanian but not the companies name.Do not include Emri mbiemri .Response only with the right structure.',
  coverLetterValidatePrompt = 'You are a helpful assistant that helps user validate the information in a json object. The information is related to user answer to these questions: For what position do you want to apply?; In which company do you want to apply?; What is the name of the person you are writing to?; What is the address of the company you want to apply at?; Which is the motive of your cover letter?; What are the topics that you want to include in your cover letter? the response object output should be {\n    title: boolean,\n    company: boolean,\n    person: boolean,\n    company_address: boolean,\n    motive: boolean,\n    topics: boolean\n  } ',
  coverLetterValidateUserPrompt = 'Title represent a job position. If topic has value, validate if includes information about user skills or experiences or motivation for applying or things related to these context. If company is empty return true for its property. If company name or company address or to person or motive are empty return true. Response with the json object for every property true when information is reletable and false if property value has unrelated information.Do not include explanations.',
}
