FROM node:18-alpine

WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY prisma ./

# Install app dependencies
RUN npm install

# Generate prisma client, leave out if generating in `postinstall` script
RUN npx prisma generate

CMD ["npm", "run", "prisma:migrate"]
