version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: 'postgresql://user:@host.docker.internal:5432/softup_x_boilerplate?schema=public'
    logging:
      driver: 'json-file'
      options:
        max-size: '10k'
        max-file: '3'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
<<<<<<< HEAD
      POSTGRES_DB: 'softup_x_boilerplate'
      POSTGRES_USER: 'user'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      DB_HOST: 'host.docker.internal'
=======
      POSTGRES_DB: 'akpa_boilerplate'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
      DB_HOST: 'postgres'
>>>>>>> c5ca3b8 (Database migrations)
volumes:
  postgres-data:
