enum Keys {
  POST_RESUME = 'POST_RESUME',
  GET_RESUME = 'GET_RESUME',
  GET_RESUMES = 'GET_RESUMES',
  PATCH_RESUME = 'PATCH_RESUME',
  POST_RESUME_RESPONSIBILITY = 'POST_RESUME_RESPONSIBILITY',
  POST_RESUME_SUMMARY = 'POST_RESUME_SUMMARY',
  POST_RESUME_ASK_WIZARD = 'POST_RESUME_ASK_WIZARD',
  POST_RESUME_FOR_JOB = 'POST_RESUME_FOR_JOB',
  DELETE_RESUME = 'DELETE_RESUME',
  POST_RESUMES_WIZARD = 'POST_RESUMES_WIZARD',
}

export default Keys;
